services:
  proxy:
    container_name: proxy
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "6969:6969"
    depends_on:
      - mosquitto
    networks:
      - default

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    volumes:
      - ./conf:/mosquitto/config
    ports:
      - "1883:1883"
    restart: unless-stopped
    networks:
      - default

networks:
  default:
    driver: bridge